### ISSUE TITLE
mkdfs incorrect output on windows

### ISSUE THREAD

**Issue by purplemarshmallow** [DragonMinded/libdragon#30] opened 2017-07-07 08:08 UTC
The program outputs a corrupt .dfs file on windows although there are no errors. When trying to use a .dfs file generated on windows with n64tool you only get an error (Couldn't pad image). Using a .dfs file from linux fixes the problem

I'm attaching the windos and linux version of the .dfs file from the spritemap example. When using a diff tool I can see the two files differ (and I assume there should not be a difference)
[spritemap-linux.zip](https://github.com/DragonMinded/libdragon/files/1130370/spritemap-linux.zip)
[spritemap-windows.zip](https://github.com/DragonMinded/libdragon/files/1130371/spritemap-windows.zip)

**Comment by Acceptable67** [comment] 2017-09-03 01:02
Also having this issue, would like some input on how to fix this. Compiling the source on windows seems to give this error, no idea why. 

If this can get fixed then I will no longer have to keep compiling on Linux and moving to Windows PC, just can do everything I need on Windows only.

**Comment by networkfusion** [comment] 2019-09-16 21:25
The issue is with the file operations adding a carriage return when on windows. The fix is to open the files in binary mode (e.g. `rb` instead of `r` and `wb` instead of `w`) Full portability fixes can be found in https://github.com/N64-tools/libdragon/blob/develop/tools/mkdfs/mkdfs.c

**Closed** 2021-01-14 10:18 UTC
